version: 2.1

jobs:
  error_handling_job:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: 
          name: When Something Fails
          command: echo "Hello Error!"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - error_handling_job